---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resume.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "resume.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- if and (eq .Values.backend.service.type "LoadBalancer") .Values.backend.service.annotations }}
  annotations:
    {{- toYaml .Values.backend.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  {{- if and (eq .Values.backend.service.type "LoadBalancer") .Values.backend.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.backend.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "resume.backend.selectorLabels" . | nindent 4 }}
