---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resume.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "resume.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "resume.frontend.selectorLabels" . | nindent 4 }}
